### ISSUE TITLE
Remove static link refering to a dead website

### ISSUE THREAD

**Issue by Blightbuster** [FluffyFishGames/ModAPI#3]
Since "modapi.de" is no longer optained by the developer and free for sale, the static reference should be removed. Also the domain could be used to upload malicious files, which is a threat to end-users.

https://github.com/FluffyFishGames/ModAPI/blob/290cfbea127d5c85e987ef7f63513986575532ca/ModAPI_Shared/Data/Game.cs#L1219

**Comment by Hellsing** [comment]
I thought you are aware that this source does not represent the current build of ModAPI, the current sources are found on my fork of ModAPI

**Comment by Hellsing** [comment]
When I find the time I will merge the fork to this official repository, but for now, due to the huge code differences due to ReSharper formatting I think it's best to keep them split.
